### ISSUE TITLE
Can't connect to interface.

### ISSUE THREAD

**Issue by watermel0nium** [Cyloci/ButtplugMc#2]
I have built with the latest commits.

No matter what interface I use, settings, or if it's even is open. All I get is:
Reconnecting to Interface...
Searching for toys...
Searching for toys...
Searching for toys...
Searching for toys...
Searching for toys...
Couldn't find any toys.

**Comment by Cyloci** [comment]
I've now finally had access to my dev machine so I've updated BPMC to 1.19.3

Could you test this again, with the newest Intiface version?

**Comment by luca31231** [comment]
Reconnecting to Interface...
Searching for toys...
Searching for toys...
Searching for toys...
Searching for toys...
Searching for toys...
Couldn't find any toys.

I got the same problem, it won't connect to intiface. im on version 0.0.4

**Comment by Cyloci** [comment]
Hey Luca, thanks for the update!

Please ensure that:
- the Intiface server is running
- your toy is visible in the Intiface UI, under Devices
- the Intiface server is listening on all  network interfaces in the Intiface, under Settings
- Is Intiface running on the same machine as the MC server?
  - If not, you will need to port forward your Intiface Server port through your firewall and router

If all of this is true, and things still don't work, please provide your logs from the MC Server and Intiface.

**Comment by luca31231** [comment]
I tried again today and it worked, I think the toy wasn't connecting properly via Bluetooth.
Thanks for the reply tho.
I hope to see more features in future updates!

**Comment by Cyloci** [comment]
Fantastic! I'll add my debug instructions above to the Readme, and then close this bad boy.
